### ISSUE TITLE
Writing bigbad bom

### ISSUE THREAD

**Issue by snhobbs** [snhobbs/HEODataBase#16]
When calling the short bom
Traceback (most recent call last):
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/hobbsDB.py", line 96, in run
    dbCore.dbCore(dataBase = dataBase, user = user, passWord = passWord)
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/dbCore.py", line 60, in dbCore
    DBCore(db).run()
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/interface/menuClasses.py", line 46, in run
    self.MenuOptions[int(userInput) -1].run()
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/dbCore.py", line 30, in run
    BigBadBomInterface(self.db).run()
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/interface/menuClasses.py", line 46, in run
    self.MenuOptions[int(userInput) -1].run()
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/bom/BigBadBom.py", line 45, in run
    generateBBB(self.db, 'LONG')
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/bom/BigBadBom.py", line 27, in generateBBB
    compObj = componentFactoryByUID(db, uid)
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/components/componentFactory.py", line 64, in componentFactoryByUID
    compBaseObj.loadPart()
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/components/componentBaseClasses.py", line 373, in loadPart
    self.readFromDB()
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/sqlWrapper/sqlWrappers.py", line 286, in readFromDB
    table.readFromDB()
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/sqlWrapper/sqlWrappers.py", line 242, in readFromDB
    resp = self.selectSql(table=self.table, columnNames = self.columnNames, conditions = self.tableCode)
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/sqlWrapper/sqlWrappers.py", line 70, in selectSql
    arg.append(self.conditionalStatement(conditions) + ';')
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/sqlWrapper/sqlWrappers.py", line 23, in conditionalStatement
    arg.append(", ".join(["'{}'".format(sqlScrub(cond[1])) for cond in conditions]))
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/sqlWrapper/sqlWrappers.py", line 23, in <listcomp>
    arg.append(", ".join(["'{}'".format(sqlScrub(cond[1])) for cond in conditions]))
IndexError: string index out of range

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/hobbsDB.py", line 96, in run
    dbCore.dbCore(dataBase = dataBase, user = user, passWord = passWord)
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/dbCore.py", line 60, in dbCore
    DBCore(db).run()
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/interface/menuClasses.py", line 46, in run
    self.MenuOptions[int(userInput) -1].run()
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/dbCore.py", line 30, in run
    BigBadBomInterface(self.db).run()
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/interface/menuClasses.py", line 46, in run
    self.MenuOptions[int(userInput) -1].run()
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/bom/BigBadBom.py", line 45, in run
    generateBBB(self.db, 'LONG')
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/bom/BigBadBom.py", line 27, in generateBBB
    compObj = componentFactoryByUID(db, uid)
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/components/componentFactory.py", line 64, in componentFactoryByUID
    compBaseObj.loadPart()
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/components/componentBaseClasses.py", line 373, in loadPart
    self.readFromDB()
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/sqlWrapper/sqlWrappers.py", line 286, in readFromDB
    table.readFromDB()
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/sqlWrapper/sqlWrappers.py", line 242, in readFromDB
    resp = self.selectSql(table=self.table, columnNames = self.columnNames, conditions = self.tableCode)
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/sqlWrapper/sqlWrappers.py", line 70, in selectSql
    arg.append(self.conditionalStatement(conditions) + ';')
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/sqlWrapper/sqlWrappers.py", line 23, in conditionalStatement
    arg.append(", ".join(["'{}'".format(sqlScrub(cond[1])) for cond in conditions]))
  File "/usr/var/lib/DataBase/virenv/lib/python3.4/site-packages/heodb/sqlWrapper/sqlWrappers.py", line 23, in <listcomp>
    arg.append(", ".join(["'{}'".format(sqlScrub(cond[1])) for cond in conditions]))
IndexError: string index out of range

**Comment by snhobbs** [comment]
No parts in database when calling the long form

**Comment by snhobbs** [comment]
String and integer compare needs to be handled differently in the python3 implimentation of pymysql

**Comment by snhobbs** [comment]
Actually the apostrophes around the column name and the value cause the literal entries to be used. In this case the integer values were entered as strings so both cannot be literal for correct interpration
